version: "3.8"

services:
  ip-geo:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./mmdb:/app/mmdb
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
