name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build binaries
        run: |
          # Linux (amd64)
          GOOS=linux GOARCH=amd64 go build -o dist/ip-geo-linux-amd64 cmd/server/main.go
          # Linux (arm64)
          GOOS=linux GOARCH=arm64 go build -o dist/ip-geo-linux-arm64 cmd/server/main.go
          # macOS (amd64)
          GOOS=darwin GOARCH=amd64 go build -o dist/ip-geo-darwin-amd64 cmd/server/main.go
          # macOS (arm64)
          GOOS=darwin GOARCH=arm64 go build -o dist/ip-geo-darwin-arm64 cmd/server/main.go
          # Windows (amd64)
          GOOS=windows GOARCH=amd64 go build -o dist/ip-geo-windows-amd64.exe cmd/server/main.go

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/ip-geo-linux-amd64
            dist/ip-geo-linux-arm64
            dist/ip-geo-darwin-amd64
            dist/ip-geo-darwin-arm64
            dist/ip-geo-windows-amd64.exe
          draft: false
          prerelease: false
          generate_release_notes: true
